#!/bin/bash
set -e
shopt -s nullglob

umask 0002
export WEBPACK_BASE_PATH=/usr/share/iserv/webpack
export NODE_PATH=/webpack/node_modules:/webpack

echo "Running webpack..."

PATTERN="bundle/*/Resources/webpack.config.js *Bundle/Resources/webpack.config.js share/app/Resources/webpack.config.js share/webpack-vendor.config.js webpack.config.js"

if [ "$PWD" != "/usr/share/iserv" ]
then
  PATTERN+=" src/*/*/Resources/webpack.config.js"
fi

for i in $PATTERN
do
    [ -f "$i" ] || continue
    /webpack/node_modules/.bin/webpack --config "$i" "$@"
done

