#!/bin/bash -e

export LC_ALL=C

if [ -f "$PWD/.winstsubdirs" ]
then
  Subdirs=$(cat "$PWD/.winstsubdirs")
  for i in $Subdirs
  do
    if [ "$i" = "common" ]
    then
      echo "Warning: common is a reserved keyword! Usement in .winstsubdirs is prohibited!"
      continue
    fi

    if [ ! -d "$PWD/winst/$i" ]
    then
      echo "Warning: Specified winst sub directory is missing!"
      continue
    fi

    if [ ! -f "$PWD/winst/$i/control" ]
    then
      echo "Warning: Control file missing! Wrong directory specified?"
      continue
    fi

    pkgID=$(awk '/^id: / { print $2 }' "$PWD"/winst/"$i"/control)

    if [ ! -e "/srv/deploy/install/$pkgID/" ]
    then
      echo "Warning: /srv/deploy/install/$pkgID/ does not exists, skipping commit!"
      continue
    fi

    find /srv/deploy/install/"$pkgID" -type f -not -path "/srv/deploy/install/$pkgID/data/*" -exec bash -e -c \
      'CurrentFile={}
      CurrentFile=${CurrentFile#/srv/deploy/install/'$pkgID'/}
      if [ "$CurrentFile" = "changelog" ]
      then
        cp --preserve=timestamps -v {} debian/winst-'"$pkgID"'.winst.changelog
      elif [ -f "winst/common/$CurrentFile" ]
      then
        cp --preserve=timestamps -v {} winst/common/$CurrentFile
      else
        cp --preserve=timestamps -v {} winst/'"$i"'/$CurrentFile
      fi' \;


      
    if [ -d "/srv/deploy/install/$pkgID/data" ] && [ -d "$PWD/data" ]
    then
      find /srv/deploy/install/"$pkgID"/data -type f -exec bash -e -c \
        'CurrentFile={}
         CurrentFile=${CurrentFile#/srv/deploy/install/'$pkgID'/data/}
         if [ -f "data/common/$CurrentFile" ]
         then
           cp --preserve=timestamps -v {} data/common/$CurrentFile
         else
           cp --preserve=timestamps -v {} data/'"$i"'/$CurrentFile
         fi' \;
     fi
  done
else
  pkgID=$(basename $PWD | sed -e 's/winst-//g')

  if [ -e "/srv/deploy/install/$pkgID/" ]
  then
    cp --preserve=timestamps -v "/srv/deploy/install/$pkgID/"{*.*,control} winst/
    cp --preserve=timestamps -v "/srv/deploy/install/$pkgID/changelog" debian/changelog
    # copy back all other other subfolders in the package directory, assuming that there are part of the winst files
    find "/srv/deploy/install/$pkgID/" -mindepth 1 -maxdepth 1 -type d ! -name "data" -exec cp --preserve=timestamps -rv {} winst/ \;
  fi

  if [ -e "/srv/deploy/install/$pkgID/data/" ]
  then
    cp --preserve=timestamps -rv "/srv/deploy/install/$pkgID/data/"* data/
  fi

  DataFiles=(data/*)
  if [ ${#DataFiles[@]} -gt 0 ]
  then
    for i in data/*
    do
      if ! [ -e "/srv/deploy/install/$pkgID/data/$(basename $i)" ]
      then
        rm -f "$i"
      fi
    done
  fi
fi
