#!/bin/bash -ex

export LC_ALL=C

pkgID=$(basename $PWD | sed -e 's/winst-//g')

if [ -e "/srv/deploy/install/$pkgID/" ]
then
  cp --preserve=timestamps -v "/srv/deploy/install/$pkgID/"{*.*,control} winst/
  cp --preserve=timestamps -v "/srv/deploy/install/$pkgID/changelog" debian/changelog
  # copy back all other other subfolders in the package directory, assuming that there are part of the winst files
  find "/srv/deploy/install/$pkgID/" -mindepth 1 -maxdepth 1 -type d ! -name "data" -exec cp --preserve=timestamps -rv {} winst/ \;
fi

if [ -e "/srv/deploy/install/$pkgID/data/" ]
then
  cp --preserve=timestamps -rv "/srv/deploy/install/$pkgID/data/"* data/
fi

DataFiles=(data/*)
if [ ${#DataFiles[@]} -gt 0 ]
then
  for i in data/*
  do
    if ! [ -e "/srv/deploy/install/$pkgID/data/$(basename $i)" ]
    then
      rm -f "$i"
    fi
  done
fi
