#!/bin/bash -e

export LC_ALL=C
export EDITOR=$(which dummy-editor)

ADDITIONALBINARYPACKAGES=$(pcregrep "^Package: (.*)$" debian/control | awk '{ print $2 }' | sed ':a;N;$!ba;s/\n/ /g')
VERSIONSTRING=$(pcregrep -M "^(.*) \((.*)\) (.*); urgency=(.*)$" debian/changelog | head -n 1)
PACKAGE=$(echo $VERSIONSTRING | awk '{ print $1 }')
VERSION=$(echo $VERSIONSTRING | awk '{ print $2 }' | sed 's/(//g' | sed 's/)//g')
UPSTREAMVERSION=${VERSION%-*}

if [ "$1" = "--native" ] || [ "$1" = "-n" ]
then
  REVISION=
  PLAINREVISION=
else
  REVISION="-"${VERSION#*-}
  PLAINREVISION=${VERSION#*-}
fi

# link deb file
if [ -e "../""$PACKAGE""_""$UPSTREAMVERSION""$REVISION""_all.deb" ] && [ -L "../""$PACKAGE""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
then
  rm -f ../"$PACKAGE"_"$UPSTREAMVERSION""$REVISION"_all.deb
elif [ -e "../""$PACKAGE""_""$UPSTREAMVERSION""$REVISION""_all.deb" ] && [ ! -L "../""$PACKAGE""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
then
  echo "Destination .deb exists and is not a symbolic link! Terminating!" >&2
  exit 1
fi

if [ ! -e "../$PACKAGE/$UPSTREAMVERSION/$PLAINREVISION" ]
then
  mkdir -pv ../package-pool/"$PACKAGE"/"$UPSTREAMVERSION"/"$PLAINREVISION"
fi

# create destionations
if [ ! -e "../package-pool/""$PACKAGE""/""$UPSTREAMVERSION""/""$PLAINREVISION""/""$PACKAGE""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
then
  touch ../package-pool/"$PACKAGE"/"$UPSTREAMVERSION"/"$PLAINREVISION"/"$PACKAGE"_"$UPSTREAMVERSION""$REVISION"_all.deb
fi

# link destinations
ln -sfv ./package-pool/"$PACKAGE"/"$UPSTREAMVERSION"/"$PLAINREVISION"/"$PACKAGE"_"$UPSTREAMVERSION""$REVISION"_all.deb ../"$PACKAGE"_"$UPSTREAMVERSION""$REVISION"_all.deb

for i in $ADDITIONALBINARYPACKAGES
do
  if ! [ "$i" = "$PACKAGE" ]
  then
    # link deb file
    if [ -e "../""$i""_""$UPSTREAMVERSION""$REVISION""_all.deb" ] && [ -L "../""$i""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
    then
      rm -f ../"$i"_"$UPSTREAMVERSION""$REVISION"_all.deb
    elif [ -e "../""$i""_""$UPSTREAMVERSION""$REVISION""_all.deb" ] && [ ! -L "../$i""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
    then
      echo "Destination .deb exists and is not a symbolic link! Terminating!" >&2
      exit 1
    fi

    if [ ! -e "../package-pool/""$PACKAGE""/""$UPSTREAMVERSION""/""$PLAINREVISION""/""$i""_""$UPSTREAMVERSION""$REVISION""_all.deb" ]
    then
      touch ../package-pool/"$PACKAGE"/"$UPSTREAMVERSION"/"$PLAINREVISION"/"$i"_"$UPSTREAMVERSION""$REVISION"_all.deb
    fi

    ln -sfv ./package-pool/"$PACKAGE"/"$UPSTREAMVERSION"/"$PLAINREVISION"/"$i"_"$UPSTREAMVERSION""$REVISION"_all.deb ../"$i"_"$UPSTREAMVERSION""$REVISION"_all.deb
  fi
done

dpkg-buildpackage -b

# remove links
rm -f ../"$PACKAGE"_"$UPSTREAMVERSION""$REVISION"_all.deb

for i in $ADDITIONALBINARYPACKAGES
do
  rm -f ../"$i"_"$UPSTREAMVERSION""$REVISION"_all.deb
done
