#!/bin/bash -e

export LC_ALL=C

VERSIONSTRING=$(pcregrep -M "^(.*) \((.*)\) (.*); urgency=(.*)$" debian/changelog | head -n 1)
PACKAGE=$(echo $VERSIONSTRING | awk '{ print $1 }')
VERSION=$(echo $VERSIONSTRING | awk '{ print $2 }' | replace '(' '' | replace ')' '')
UPSTREAMVERSION=${VERSION%-*}

# create pseudo orig archive to prevent dpkg abort on debian systems
if [ -e "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz" ]
then
  rm "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz"
fi

tar --files-from /dev/null -Jcf "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz"

if [ -d "debian/patches/" ]
then
  rm -rf debian/patches/
fi

dpkg-source --commit ./ upstream

dpkg-buildpackage
