#!/bin/bash -e

export LC_ALL=C
export EDITOR=$(which dummy-editor)

VERSIONSTRING=$(pcregrep -M "^(.*) \((.*)\) (.*); urgency=(.*)$" debian/changelog | head -n 1)
PACKAGE=$(echo $VERSIONSTRING | awk '{ print $1 }')
VERSION=$(echo $VERSIONSTRING | awk '{ print $2 }' | replace '(' '' | replace ')' '')
UPSTREAMVERSION=${VERSION%-*}

# create pseudo orig archive to prevent dpkg abort on debian systems
if [ -e "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz" ]
then
  rm "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz"
fi

tar --files-from /dev/null -Jcf "../""$PACKAGE""_""$UPSTREAMVERSION"".orig.tar.xz"

# Merge all files into a patch.
if [ -d "debian/patches/" ]
then
  rm -rf debian/patches/
fi

dpkg-source --commit ./ upstream

# Whitelist all
echo > ./debian/source/include-binaries
find -type f -not -path "./debian/*" -not -path "./git/*" -not -path "./gitignore" -exec $(which bash) -c "echo {} >> debian/source/include-binaries" \;
sed -i "s/^\.\///g" debian/source/include-binaries

dpkg-buildpackage

# hard reset patch counter
rm -rf .pc/
