#!/bin/bash -e

export LC_ALL=en_US.utf8
export EDITOR=/usr/bin/vim

CONFIGDIRPREFIX=/usr/local

if [ "$#" -lt "1" ]
then
  echo "You need to supply a version number with $0 <number>." >&2
  exit 1
fi

if [ "$#" -gt "3" ]
then 
  SINCE="$4" 
else
  SINCE=""
fi;

gbp dch -U $(if [ "$#" -gt "1" ]; then echo $2; else echo "medium"; fi) -D experimental --full -R -N $1 --since "$(if [ "$SINCE" = "" ]; then git log --all | grep -B 4 -m 1 -i "Update changelog" | head -n 1 | awk '{ print $2 }'; else echo $SINCE; fi;)"

# replace maintainer
Maintainer=($CONFIGDIRPREFIX/etc/stsbl/repository/package-maintainer)
sed -i "s/-- $DEBFULLNAME <$DEBEMAIL>/-- $Maintainer/g" debian/changelog

if [ "$#" -gt "2" ]
then

git add debian/changelog
git commit -m "Update changelog for $1 release."
