#!/bin/bash -e

export LC_ALL=en_US.utf8
export EDITOR=/usr/bin/vim

CONFIGDIRPREFIX=/usr/local

if [ "$#" -lt "1" ]
then
  echo "You need to supply a version number with $0 <number>." >&2
  exit 1
fi

if [ "$#" -gt "1" ]
then
  Urgency="$2"
else
  Urgency="medium"
fi

if [ "$#" -gt "2" ] && [ ! -z "$3" ]
then
  Since="$3"
else
  Since=$(git log --all | grep -B 4 -m 1 -i "Update changelog" | head -n 1 | awk '{ print $2 }')
fi

gbp dch -U "$Urgency" -D experimental --full --git-author -R -N "$1" --since "$Since"

# replace maintainer
#Maintainer=$(cat "$CONFIGDIRPREFIX"/etc/stsbl/repository/maintainer)
#sed -i "s/-- $(echo $DEBFULLNAME) <$(echo $DEBEMAIL)>/-- $(echo $Maintainer)/g" debian/changelog

git add debian/changelog
git commit -m "Update changelog for $1 release."
