#!/bin/bash

export DEBEMAIL=repository@stsbl.de
export DEBFULLNAME=Stadtteilschule\ Blankenese

PKG=$(basename $PWD)
WINSTPKG=${PKG#winst-}

if [ ! -f "control" ] && [ ! -f "install/$WINSTPKG/control" ]
then
  echo -e "No control file found!\nWrong directory?" 1>&2
  exit 1
fi

FILE=control

if [ ! -f "control" ]
then
  FILE=install/$WINSTPKG/control
fi

# extract version number
VER=$(awk 'END { print ver "-" rel } \
  /^version: / { ver = $2 } \
  /^packageVersion: / { rel = $2 }' $FILE)

# extract package name
NAME=$(grep -m 1 -E "^name:" $FILE | sed 's/name: //')

# extract package description
DESCRIPTION=$(grep -m 1 -E "^description:" $FILE | sed 's/description: //')

dh_make -c mit -i -n -p $(basename $PWD)_$VER

rm -f debian/*.{ex,EX}
rm -f debian/README*
rm -f debian/docs

# remove clutter
sed -i '/Source: <url:\/\/example.com>/d' debian/copyright
sed -i "/# Please also look if there are files or directories which have a/d" debian/copyright
sed -i "/# different copyright\/license attached and list them here./d" debian/copyright
sed -i "/# Please avoid to pick license terms that are more restrictive than the/d" debian/copyright
sed -i "/# packaged work, as it may make Debian's contributions unacceptable upstream./d" debian/copyright

sed -i '/Homepage: <insert the upstream URL, if relevant>/d' debian/control
sed -i '/#Vcs-Git: git:\/\/anonscm.debian.org\/collab-maint\/'$PKG'.git/d' debian/control
sed -i '/#Vcs-Browser: http:\/\/anonscm.debian.org\/?p=collab-maint\/'$PKG'.git;a=summary/d' debian/control

# fill control
sed -i "s/Description: <insert up to 60 chars description>/Description: $NAME/g" debian/control
sed -i "s/ <insert long description, indented with spaces>/ $DESCRIPTION\nTag: suite::iserv:deploy, role::package/g" debian/control
sed -i "s/Section: unknown/Section: misc/g" debian/control
sed -i "s/Priority: optional/Priority: extra/g" debian/control

if [ ! -e ".gitignore" ]
then
  # create .gitignore
  echo "debian/$(basename $PWD)/*" > .gitignore
  echo "debian/$(basename $PWD).substvars" >> .gitignore
  echo "debian/$(basename $PWD).debhelper.log" >> .gitignore
  echo "debian/files" >> .gitignore
  echo "debian/debhelper-build-stamp" >> .gitignore
fi

# copy rules
cp -a /usr/share/iserv/dev/debian-rules.template debian/rules
