#!/bin/bash -e

export DEBFULLNAME=Stadtteilschule\ Blankenese
export DEBEMAIL=repository@stsbl.de

if [ -z "$1" ]
then
 echo "Usement: $(basename $0) [VERSION]"
 exit 1
fi

dh_make -c mit -p $(basename $PWD)_$1 -i -n

rm -f debian/*.{ex,EX}
rm -f debian/README*
rm -f debian/docs

# remove clutter
sed -i '/Source: <url:\/\/example.com>/d' debian/copyright
sed -i "/# Please also look if there are files or directories which have a/d" debian/copyright
sed -i "/# different copyright\/license attached and list them here./d" debian/copyright
sed -i "/# Please avoid to pick license terms that are more restrictive than the/d" debian/copyright
sed -i "/# packaged work, as it may make Debian's contributions unacceptable upstream./d" debian/copyright

if [ ! -e ".gitignore" ]
then
  # create .gitignore
  echo "debian/$(basename $PWD)/*" > .gitignore
  echo "debian/$(basename $PWD).substvars" >> .gitignore
  echo "debian/$(basename $PWD).debhelper.log" >> .gitignore
  echo "debian/files" >> .gitignore
  echo "debian/debhelper-build-stamp" >> .gitignore
fi
