#!/bin/bash -ex

export LC_ALL=C
helper=$(which stsbl-dev-python-helper)

for i in db lib iconf src priv share config sbin bin iservchk roles appdata
do
  if [ ! -e "$PWD/$i/" ]
  then
    continue
  fi

  mkdir -pv "$i.collect/$i"
  
  if [ "$i" = "share" ]
  then
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect"/{} \;
    find $i/ -mindepth 1 -type f -exec bash -c "file={}; $helper \${file/share\///} $i 'share/' '' '' 'share'" \;
  elif [ "$i" = "config" ]
  then
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect"/{} \;
    find $i/ -mindepth 1 -type f -exec $helper {} $i '' 'iservcfg/' \;
  elif [ "$i" = "iservchk" ]
  then
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect"/{} \;
    find $i/ -mindepth 1 -type f -exec $helper {} $i '' 'iconf/etc/iserv/chk.d/' 'iservchk' \;
  elif [ "$i" = "lib" ] || [ "$i" = "sbin" ] || [ "$i" = "bin" ]
  then
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect"/{} \;
    find $i/ -mindepth 1 -type f -exec bash -ex -c 'subject={}; echo $subject; cp -v --preserve=timestamps "/usr/'$(path=$(echo $i | tr "/" "\n"); if [ "${path[0]}" = "lib" ]; then echo "lib/iserv"; else echo $i; fi)'/$(echo $subject | sed s/lib//g)" "'$i'.collect/'$i'/$(echo $(dirname {}) | sed s/lib//g)/"' \;
  elif [ "$i" = "appdata" ]
  then
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect"/{} \;
    
  else
    find $i/ -mindepth 1 -type d -exec mkdir -pv "$i.collect/"{} \;
    find $i/ -mindepth 1 -type f -exec $helper {} $i \;
  fi

  rm -rfv $i/
  mv -v $i".collect"/$i/ $i/

  rm -rfv ./$i".collect"/
done
