#!/bin/bash

export LC_ALL=C

if [ -d "usr/" ]
then
  cp -rv usr/* /usr/
fi

if [ -d "config/" ]
then
  cp -rv config/* /usr/share/iserv/iservcfg/config/
fi

if [ -d "iconf/" ]
then
  cp -rv iconf/* /usr/share/iserv/iconf/
fi

if [ -d "iservchk/" ]
then
  cp -rv iservchk/* /usr/share/iserv/iconf/etc/iserv/chk.d/
fi

if [ -d "priv/" ]
then
  cp -rv priv/* /usr/share/iserv/priv/
fi

if [ -d "share/" ]
then
  cp -rv share/* /usr/share/iserv/
fi

if [ -d "src/" ]
then
  cp -rv src/* /usr/share/iserv/src/
fi

if [ -d "lib/" ]
then
  cp -rv lib/* /usr/lib/iserv/
fi

if [ -d "bin/" ]
then
  cp -rv bin/* /usr/bin/
fi

if [ -d "sbin/" ]
then
  cp -rv sbin/* /usr/sbin/
fi

if [ -d "roles/" ]
then
  cp -rv roles/* /usr/share/iserv/roles/
fi

if [ -d "db/" ]
then
  cp -rv db/* /usr/share/iserv/db/
fi

if [ -d "appdata/" ]
then
  cp -rv appdata/* /srv/appdata/
fi
